import About_Body from '@/public/Component/About_Components/About_Body/About_body';
import React from 'react'

export const metadata = {
    title: "about page",
    description: "Generated by create next app",
  };


const About = () => {
    return(
        <div>
            <About_Body/>
        </div>
    )
}

export default About; 